/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import ControlNavegacion.ControlNavegacion;
import dtos.ClienteMesaDTO;
import dtos.ClienteMesaProductoDTO;
import dtos.DetalleComandaDTO;
import dtos.ProductoDTO;
import entidades.Producto;
import enums.Tipo;
import excepciones.NegocioException;
import interfaces.IManejadorDeObjetos;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import manejadorDeObjetos.ManejadorDeObjetos;
import javax.swing.JOptionPane;
/**
 *
 * @author Ramón Zamudio
 */
public class AñadirProductoComanda extends javax.swing.JFrame {
    ControlNavegacion control;
    JComboBox<Tipo> tipoComboBox;
    List<DetalleComandaDTO>listaDetallesComanda;
    ClienteMesaDTO clienteMesa;
    /**
     * Creates new form AñadirProductoComanda
     */
    public AñadirProductoComanda(ControlNavegacion control,ClienteMesaDTO clienteMesa) {
        System.out.println(clienteMesa);
        initComponents();
        this.control = control;
        this.clienteMesa = clienteMesa;
        tipoComboBox = new JComboBox<>(new DefaultComboBoxModel<>(Tipo.values()));
        tipoComboBox.setBounds(410, 145,130,70);
        add(tipoComboBox); 
        getContentPane().setBackground(new java.awt.Color(248, 248, 241));
        listaDetallesComanda = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setText("Casa magna");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTextField1.setColumns(15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(970, 970, 970))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(43, 43, 43)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        control.openFormPantallaPrincipalRol();
        dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String busqueda = jTextField1.getText();
        jPanel1.removeAll();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        try {
            List<ProductoDTO> listaProductos;
            if (jTextField1.getText().isEmpty()) {
                listaProductos = control.obtenerPorTipo((Tipo) tipoComboBox.getSelectedItem());
            } else {
                listaProductos = control.obtenerPorNombre(busqueda);
            }

            jPanel1.removeAll();

            for (ProductoDTO producto : listaProductos) {
                DetalleComandaDTO detalleComanda = new DetalleComandaDTO();
                JPanel productoPanel = new JPanel();
                productoPanel.setLayout(new BoxLayout(productoPanel, BoxLayout.Y_AXIS));
                productoPanel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
                productoPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 110));
                productoPanel.setBackground(Color.WHITE);

                JLabel nombreLabel = new JLabel(producto.getNombre(), SwingConstants.CENTER);
                nombreLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                nombreLabel.setFont(new Font("Arial", Font.BOLD, 14));

                JPanel contadorPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
                contadorPanel.setOpaque(false);

                JButton btnMenos = new JButton("-");
                JLabel cantidadLabel = new JLabel("0");
                JButton btnMas = new JButton("+");

                btnMenos.setPreferredSize(new Dimension(40, 40));
                btnMas.setPreferredSize(new Dimension(40, 40));
                cantidadLabel.setPreferredSize(new Dimension(30, 30));
                cantidadLabel.setFont(new Font("Arial", Font.BOLD, 16));
                cantidadLabel.setHorizontalAlignment(SwingConstants.CENTER);

                final int[] cantidad = {0};

                btnMas.addActionListener(e -> {
                    cantidad[0]++;
                    cantidadLabel.setText(String.valueOf(cantidad[0]));

                    // Verifica si el producto ya existe en la lista de detalles
                    boolean productoExiste = false;
                    for (DetalleComandaDTO detalle : listaDetallesComanda) {
                        if (detalle.getProducto().getNombre().equals(producto.getNombre())) {
                            detalle.setCantidad(cantidad[0]);
                            detalle.setPrecioUnitario(producto.getPrecio());
                            detalle.setImporte(producto.getPrecio() * cantidad[0]);
                            productoExiste = true;
                        }
                    }

                    if (!productoExiste) {
                        DetalleComandaDTO nuevoDetalleComanda = new DetalleComandaDTO();
                        nuevoDetalleComanda.setProducto(new Producto(producto.getNombre(), producto.getPrecio(), producto.isEstado()));
                        nuevoDetalleComanda.setCantidad(cantidad[0]);
                        nuevoDetalleComanda.setPrecioUnitario(producto.getPrecio());
                        nuevoDetalleComanda.setImporte(producto.getPrecio() * cantidad[0]);
                        listaDetallesComanda.add(nuevoDetalleComanda);
                    }
                });

                btnMenos.addActionListener(e -> {
                    if (cantidad[0] > 0) {
                        cantidad[0]--;
                        cantidadLabel.setText(String.valueOf(cantidad[0]));
                        for (DetalleComandaDTO detalle : listaDetallesComanda) {
                            if (detalle.getProducto().getNombre().equals(producto.getNombre())) {
                                // Si el producto existe, actualiza la cantidad y el importe
                                detalle.setCantidad(cantidad[0]);
                                detalle.setPrecioUnitario(producto.getPrecio());
                                detalle.setImporte(producto.getPrecio() * cantidad[0]);
                            }
                        }
                    }
                });

                contadorPanel.add(btnMenos);
                contadorPanel.add(cantidadLabel);
                contadorPanel.add(btnMas);

                JButton btnNotas = new JButton("Notas");
                btnNotas.setAlignmentX(Component.CENTER_ALIGNMENT);
                btnNotas.addActionListener(e -> {
                    JTextArea textArea = new JTextArea(10, 30);
                    textArea.setLineWrap(true);
                    textArea.setWrapStyleWord(true);

                    JScrollPane scrollPane = new JScrollPane(textArea);

                    int option = JOptionPane.showConfirmDialog(
                        null,
                        scrollPane,
                        "Agregar notas para " + producto.getNombre(),
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE
                    );

                    if (option == JOptionPane.OK_OPTION) {
                        String notas = textArea.getText();
                        System.out.println("Notas capturadas: " + notas);
                        for (DetalleComandaDTO detalle : listaDetallesComanda) {
                            if (detalle.getProducto().getNombre().equals(producto.getNombre())) {
                                detalle.setNotas(notas);
                            }
                        }
                    }
                });

                productoPanel.add(nombreLabel);
                productoPanel.add(contadorPanel);
                productoPanel.add(btnNotas);

                jPanel1.add(productoPanel);
            }

            jPanel1.revalidate();
            jPanel1.repaint();
        } catch (Exception ex) {
            try {
                throw new NegocioException("Error al buscar el producto");
            } catch (NegocioException ex1) {
                Logger.getLogger(BuscadorDeProductosFrame.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ClienteMesaProductoDTO clienteMesaP = new ClienteMesaProductoDTO(clienteMesa.getMesa(), clienteMesa.getCliente(), listaDetallesComanda);
       control.openFormResumenComanda(clienteMesaP);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirProductoComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirProductoComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirProductoComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirProductoComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IManejadorDeObjetos manejador = new ManejadorDeObjetos();
                ControlNavegacion control = new ControlNavegacion(manejador);
                ClienteMesaDTO cliente = new ClienteMesaDTO();
                new AñadirProductoComanda(control,cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
